export const BIBLE_BOOKS = [
  { name: "Genesis", abbreviation: "Gen", chapters: 50, testament: "old" },
  { name: "Exodus", abbreviation: "Exod", chapters: 40, testament: "old" },
  { name: "Leviticus", abbreviation: "Lev", chapters: 27, testament: "old" },
  { name: "Numbers", abbreviation: "Num", chapters: 36, testament: "old" },
  { name: "Deuteronomy", abbreviation: "Deut", chapters: 34, testament: "old" },
  { name: "Joshua", abbreviation: "Josh", chapters: 24, testament: "old" },
  { name: "Judges", abbreviation: "Judg", chapters: 21, testament: "old" },
  { name: "Ruth", abbreviation: "Ruth", chapters: 4, testament: "old" },
  { name: "1 Samuel", abbreviation: "1Sam", chapters: 31, testament: "old" },
  { name: "2 Samuel", abbreviation: "2Sam", chapters: 24, testament: "old" },
  { name: "1 Kings", abbreviation: "1Kgs", chapters: 22, testament: "old" },
  { name: "2 Kings", abbreviation: "2Kgs", chapters: 25, testament: "old" },
  { name: "1 Chronicles", abbreviation: "1Chr", chapters: 29, testament: "old" },
  { name: "2 Chronicles", abbreviation: "2Chr", chapters: 36, testament: "old" },
  { name: "Ezra", abbreviation: "Ezra", chapters: 10, testament: "old" },
  { name: "Nehemiah", abbreviation: "Neh", chapters: 13, testament: "old" },
  { name: "Esther", abbreviation: "Esth", chapters: 10, testament: "old" },
  { name: "Job", abbreviation: "Job", chapters: 42, testament: "old" },
  { name: "Psalms", abbreviation: "Ps", chapters: 150, testament: "old" },
  { name: "Proverbs", abbreviation: "Prov", chapters: 31, testament: "old" },
  { name: "Ecclesiastes", abbreviation: "Eccl", chapters: 12, testament: "old" },
  { name: "Song of Solomon", abbreviation: "Song", chapters: 8, testament: "old" },
  { name: "Isaiah", abbreviation: "Isa", chapters: 66, testament: "old" },
  { name: "Jeremiah", abbreviation: "Jer", chapters: 52, testament: "old" },
  { name: "Lamentations", abbreviation: "Lam", chapters: 5, testament: "old" },
  { name: "Ezekiel", abbreviation: "Ezek", chapters: 48, testament: "old" },
  { name: "Daniel", abbreviation: "Dan", chapters: 12, testament: "old" },
  { name: "Hosea", abbreviation: "Hos", chapters: 14, testament: "old" },
  { name: "Joel", abbreviation: "Joel", chapters: 3, testament: "old" },
  { name: "Amos", abbreviation: "Amos", chapters: 9, testament: "old" },
  { name: "Obadiah", abbreviation: "Obad", chapters: 1, testament: "old" },
  { name: "Jonah", abbreviation: "Jonah", chapters: 4, testament: "old" },
  { name: "Micah", abbreviation: "Mic", chapters: 7, testament: "old" },
  { name: "Nahum", abbreviation: "Nah", chapters: 3, testament: "old" },
  { name: "Habakkuk", abbreviation: "Hab", chapters: 3, testament: "old" },
  { name: "Zephaniah", abbreviation: "Zeph", chapters: 3, testament: "old" },
  { name: "Haggai", abbreviation: "Hag", chapters: 2, testament: "old" },
  { name: "Zechariah", abbreviation: "Zech", chapters: 14, testament: "old" },
  { name: "Malachi", abbreviation: "Mal", chapters: 4, testament: "old" },
  { name: "Matthew", abbreviation: "Matt", chapters: 28, testament: "new" },
  { name: "Mark", abbreviation: "Mark", chapters: 16, testament: "new" },
  { name: "Luke", abbreviation: "Luke", chapters: 24, testament: "new" },
  { name: "John", abbreviation: "John", chapters: 21, testament: "new" },
  { name: "Acts", abbreviation: "Acts", chapters: 28, testament: "new" },
  { name: "Romans", abbreviation: "Rom", chapters: 16, testament: "new" },
  { name: "1 Corinthians", abbreviation: "1Cor", chapters: 16, testament: "new" },
  { name: "2 Corinthians", abbreviation: "2Cor", chapters: 13, testament: "new" },
  { name: "Galatians", abbreviation: "Gal", chapters: 6, testament: "new" },
  { name: "Ephesians", abbreviation: "Eph", chapters: 6, testament: "new" },
  { name: "Philippians", abbreviation: "Phil", chapters: 4, testament: "new" },
  { name: "Colossians", abbreviation: "Col", chapters: 4, testament: "new" },
  { name: "1 Thessalonians", abbreviation: "1Thess", chapters: 5, testament: "new" },
  { name: "2 Thessalonians", abbreviation: "2Thess", chapters: 3, testament: "new" },
  { name: "1 Timothy", abbreviation: "1Tim", chapters: 6, testament: "new" },
  { name: "2 Timothy", abbreviation: "2Tim", chapters: 4, testament: "new" },
  { name: "Titus", abbreviation: "Titus", chapters: 3, testament: "new" },
  { name: "Philemon", abbreviation: "Phlm", chapters: 1, testament: "new" },
  { name: "Hebrews", abbreviation: "Heb", chapters: 13, testament: "new" },
  { name: "James", abbreviation: "Jas", chapters: 5, testament: "new" },
  { name: "1 Peter", abbreviation: "1Pet", chapters: 5, testament: "new" },
  { name: "2 Peter", abbreviation: "2Pet", chapters: 3, testament: "new" },
  { name: "1 John", abbreviation: "1John", chapters: 5, testament: "new" },
  { name: "2 John", abbreviation: "2John", chapters: 1, testament: "new" },
  { name: "3 John", abbreviation: "3John", chapters: 1, testament: "new" },
  { name: "Jude", abbreviation: "Jude", chapters: 1, testament: "new" },
  { name: "Revelation", abbreviation: "Rev", chapters: 22, testament: "new" },
] as const;

export const DAILY_VERSES = [
  {
    reference: "Philippians 4:13",
    text: "I can do all things through Christ who strengthens me.",
    theme: "strength",
  },
  {
    reference: "Jeremiah 29:11",
    text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.",
    theme: "hope",
  },
  {
    reference: "Psalm 23:1",
    text: "The Lord is my shepherd; I shall not want.",
    theme: "provision",
  },
  {
    reference: "Romans 8:28",
    text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    theme: "purpose",
  },
  {
    reference: "Isaiah 41:10",
    text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.",
    theme: "courage",
  },
  {
    reference: "Proverbs 3:5-6",
    text: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.",
    theme: "trust",
  },
  {
    reference: "Psalm 46:10",
    text: "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.",
    theme: "peace",
  },
  {
    reference: "Matthew 11:28",
    text: "Come to me, all you who are weary and burdened, and I will give you rest.",
    theme: "rest",
  },
  {
    reference: "2 Corinthians 5:17",
    text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!",
    theme: "renewal",
  },
  {
    reference: "Psalm 119:105",
    text: "Your word is a lamp for my feet, a light on my path.",
    theme: "guidance",
  },
  {
    reference: "John 3:16",
    text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
    theme: "love",
  },
  {
    reference: "Romans 12:2",
    text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
    theme: "transformation",
  },
  {
    reference: "Galatians 5:22-23",
    text: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.",
    theme: "spiritual fruit",
  },
  {
    reference: "Psalm 91:1-2",
    text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the Lord, 'He is my refuge and my fortress, my God, in whom I trust.'",
    theme: "protection",
  },
  {
    reference: "Lamentations 3:22-23",
    text: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
    theme: "faithfulness",
  },
  {
    reference: "1 John 4:18",
    text: "There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.",
    theme: "fearlessness",
  },
  {
    reference: "Ephesians 2:8-9",
    text: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.",
    theme: "grace",
  },
  {
    reference: "Joshua 1:9",
    text: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.",
    theme: "courage",
  },
  {
    reference: "Psalm 37:4",
    text: "Take delight in the Lord, and he will give you the desires of your heart.",
    theme: "delight",
  },
  {
    reference: "Matthew 6:33",
    text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
    theme: "priorities",
  },
  {
    reference: "1 Corinthians 13:4-7",
    text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.",
    theme: "love",
  },
  {
    reference: "Psalm 34:18",
    text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.",
    theme: "comfort",
  },
  {
    reference: "2 Timothy 1:7",
    text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.",
    theme: "empowerment",
  },
  {
    reference: "Hebrews 11:1",
    text: "Now faith is confidence in what we hope for and assurance about what we do not see.",
    theme: "faith",
  },
  {
    reference: "Micah 6:8",
    text: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.",
    theme: "justice",
  },
  {
    reference: "Isaiah 40:31",
    text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.",
    theme: "endurance",
  },
  {
    reference: "Psalm 139:14",
    text: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.",
    theme: "identity",
  },
  {
    reference: "Colossians 3:23",
    text: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.",
    theme: "diligence",
  },
  {
    reference: "1 Thessalonians 5:16-18",
    text: "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus.",
    theme: "gratitude",
  },
  {
    reference: "James 1:2-3",
    text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.",
    theme: "perseverance",
  },
  {
    reference: "Psalm 27:1",
    text: "The Lord is my light and my salvation — whom shall I fear? The Lord is the stronghold of my life — of whom shall I be afraid?",
    theme: "confidence",
  },
];

export const READING_PLANS = [
  {
    id: "gospels-30",
    title: "Journey Through the Gospels",
    description: "Walk with Jesus through all four Gospel accounts in 30 days. Experience the life, ministry, death, and resurrection of Christ.",
    duration_days: 30,
    category: "gospel" as const,
    difficulty: "beginner" as const,
    participants_count: 12847,
    readings: [
      { day: 1, title: "The Word Made Flesh", scripture_references: ["John 1:1-18"], commentary: "John opens his Gospel with a profound theological statement: Jesus is the eternal Word (Logos) of God. Before creation, before time itself, the Word existed in perfect communion with the Father. This Word is not merely spoken — He is the living expression of God's character, wisdom, and love. When the Word became flesh, the invisible God became visible, touchable, and knowable.", reflection_question: "How does knowing that Jesus has been present from the very beginning of creation change how you approach Him today?" },
      { day: 2, title: "The Birth of Hope", scripture_references: ["Luke 1:26-56", "Luke 2:1-20"], commentary: "The angel Gabriel's announcement to Mary is one of the most tender moments in Scripture. A young woman in an obscure village receives the most extraordinary news in human history. Mary's response — 'I am the Lord's servant' — reveals a heart of profound faith and surrender. Her Magnificat that follows is a revolutionary song about God's upside-down kingdom where the humble are lifted up and the mighty brought low.", reflection_question: "What area of your life is God asking you to respond with 'I am the Lord's servant'?" },
      { day: 3, title: "Baptism and Temptation", scripture_references: ["Matthew 3:13-17", "Matthew 4:1-11"], commentary: "Jesus' baptism marks the beginning of His public ministry, affirmed by the Father's voice and the Spirit's descent. Immediately after this mountaintop experience, Jesus is led into the wilderness to face temptation. Notice that Jesus combats every temptation with Scripture. He shows us that spiritual battles are won not through our own strength but through the living Word of God.", reflection_question: "What Scripture could you hold onto during your current season of testing?" },
      { day: 4, title: "The First Disciples", scripture_references: ["Mark 1:14-20", "John 1:35-51"], commentary: "Jesus doesn't begin His ministry alone. He calls ordinary people — fishermen, tax collectors — to follow Him. The call is simple yet radical: 'Follow me.' These men left their nets, their boats, their livelihoods. They didn't fully understand who Jesus was, but something in His invitation compelled them to leave everything behind.", reflection_question: "What 'nets' might Jesus be asking you to set down in order to follow Him more closely?" },
      { day: 5, title: "The Sermon on the Mount", scripture_references: ["Matthew 5:1-48"], commentary: "The Beatitudes turn worldly values upside down. Blessed are the poor in spirit, the mourning, the meek, the hungry. Jesus redefines what it means to live well. This is not a list of rules but a portrait of the human heart transformed by grace. Each beatitude describes a different facet of the life God desires for His children.", reflection_question: "Which beatitude resonates most with where you are in life right now?" },
    ],
  },
  {
    id: "psalms-30",
    title: "30 Days of Psalms",
    description: "Discover the prayer book of the Bible. From praise to lament, the Psalms give voice to every human emotion before God.",
    duration_days: 30,
    category: "wisdom" as const,
    difficulty: "beginner" as const,
    participants_count: 9432,
    readings: [
      { day: 1, title: "The Way of the Righteous", scripture_references: ["Psalm 1"], commentary: "Psalm 1 serves as the gateway to the entire Psalter. It presents two paths: the way of the righteous who delight in God's Word, and the way of the wicked who are blown away like chaff. The righteous person is compared to a tree planted by streams of water — deeply rooted, consistently fruitful, and evergreen. This tree doesn't just survive; it thrives.", reflection_question: "What does it look like practically for you to 'delight in the law of the Lord' today?" },
      { day: 2, title: "The Shepherd Psalm", scripture_references: ["Psalm 23"], commentary: "Perhaps the most beloved chapter in all of Scripture, Psalm 23 paints a picture of God as the Good Shepherd. David, who knew what it meant to tend sheep, understood that sheep need constant guidance, protection, and provision. In green pastures and dark valleys alike, the Shepherd is present. His rod corrects and His staff comforts.", reflection_question: "Are you currently in a 'green pasture' season or a 'valley' season? How is the Shepherd present with you?" },
      { day: 3, title: "A Cry from the Depths", scripture_references: ["Psalm 42", "Psalm 43"], commentary: "These twin psalms express a deep spiritual thirst. The psalmist feels forgotten by God, overwhelmed by waves of sorrow, yet keeps returning to a refrain of hope: 'Why are you downcast, O my soul? Put your hope in God.' This is the honest prayer of someone who is struggling but refusing to let go of faith. God invites our honest lament.", reflection_question: "When have you felt your soul 'downcast'? How did you find your way back to hope?" },
    ],
  },
  {
    id: "paul-epistles-21",
    title: "Letters of Paul",
    description: "Journey through Paul's transformative letters. Discover theology that changed the world and practical wisdom for daily faith.",
    duration_days: 21,
    category: "epistles" as const,
    difficulty: "intermediate" as const,
    participants_count: 7215,
    readings: [
      { day: 1, title: "Righteousness by Faith", scripture_references: ["Romans 1:1-17", "Romans 3:21-31"], commentary: "Paul's letter to the Romans is his theological masterpiece. He establishes the foundational truth of Christianity: we are made right with God not through our own efforts but through faith in Jesus Christ. The righteous shall live by faith — this single phrase ignited the Reformation and continues to liberate hearts burdened by trying to earn God's approval.", reflection_question: "In what ways do you still try to 'earn' God's love rather than simply receiving it?" },
    ],
  },
  {
    id: "whole-bible-365",
    title: "Through the Bible in a Year",
    description: "Read the entire Bible from Genesis to Revelation with daily AI commentary to guide your understanding.",
    duration_days: 365,
    category: "whole_bible" as const,
    difficulty: "advanced" as const,
    participants_count: 3891,
    readings: [
      { day: 1, title: "In the Beginning", scripture_references: ["Genesis 1-3"], commentary: "The opening chapters of Genesis establish everything: God is the sovereign Creator, humanity bears His image, sin enters through disobedience, and yet even in judgment there is grace. God clothes Adam and Eve before sending them from the garden — a beautiful foreshadowing of how He covers our shame with His love.", reflection_question: "What does it mean to you personally that you are made in the image of God?" },
    ],
  },
];

export function getDailyVerse(): { reference: string; text: string; theme: string; date: string } {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24)
  );
  const index = dayOfYear % DAILY_VERSES.length;
  return {
    ...DAILY_VERSES[index],
    date: today.toISOString().split("T")[0],
  };
}
